#!/bin/sh

set_gpio()
{
    local NET_NAME=$1
    local OUT_VAL=$2
    mapfile -t -d " " GPIO_INFO < <(gpiofind "$NET_NAME")
    if [ "${#GPIO_INFO[@]}" -ne 2 ]; then
        echo "set_gpio: can not find gpio, $NET_NAME"
        return 1
    fi

    echo -n "set_gpio: set $NET_NAME = $OUT_VAL"
    if ! gpioset "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}"="$OUT_VAL"; then
        echo " failed"
        return 1
    fi

    echo " success"
    return 0
}

uart_mux_select()
{
    local BLADE_INDEX=$1
    if [ "$BLADE_INDEX" = 0 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 1 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 2 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 3 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 4 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 5 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 6 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 7 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 0
    elif [ "$BLADE_INDEX" = 8 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 9 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 10 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 11 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 0
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 12 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 13 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 0
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 14 ]; then
        set_gpio BLADE_UART_SEL0 0
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 1
    elif [ "$BLADE_INDEX" = 15 ]; then
        set_gpio BLADE_UART_SEL0 1
        set_gpio BLADE_UART_SEL1 1
        set_gpio BLADE_UART_SEL2 1
        set_gpio BLADE_UART_SEL3 1
    else
        echo "uart_mux_select: unknow blade index ($BLADE_INDEX)"
        return 1
    fi

    return 0
}

BLADE_INDEX=$1
uart_mux_select $BLADE_INDEX

