#!/bin/bash

# Set chassis current power state to On
busctl set-property xyz.openbmc_project.State.Chassis0 /xyz/openbmc_project/state/chassis0 xyz.openbmc_project.State.Chassis CurrentPowerState s xyz.openbmc_project.State.Chassis.PowerState.On
# Turn on the power on LED
busctl set-property xyz.openbmc_project.LED.GroupManager  /xyz/openbmc_project/led/groups/power_on xyz.openbmc_project.Led.Group Asserted b true